# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  clinicalapi:
    image: clinicalapi
    build:
      context: .
      dockerfile: Clinical.API/Dockerfile
      args:
        - configuration=Debug
    ports:
      - 5123:5123
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - ~/.vsdbg:/remote_debugger:rw
